[package]
name = "rust-todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.8"
log = "0.4.19"
serde = { version = "1.0.164", features = ["derive"] }
simplelog = "0.12.1"
toml = "0.7.5"
